FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster==1.7.7 \
    dagster-postgres==0.23.7 \
    dagster-pipes==1.7.7 \
    psycopg2-binary==2.9.9 \
    boto3==1.34.69 \
    pandas==2.2.2 \
    scikit-learn==1.4.2 \
    joblib==1.4.2 \
    kafka-python==2.0.2 \
    redis==5.0.4

WORKDIR /opt/dagster/app

COPY pipelines/ .

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "pipeline.py"]