FROM python:3.11-slim

RUN pip install --no-cache-dir --timeout=300 --retries=5 dagster==1.7.7
RUN pip install --no-cache-dir --timeout=300 --retries=5 dagster-postgres==0.23.7
RUN pip install --no-cache-dir --timeout=300 --retries=5 dagster-webserver==1.7.7

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

RUN echo "storage:\n  postgres:\n    postgres_db:\n      username:\n        env: DAGSTER_POSTGRES_USER\n      password:\n        env: DAGSTER_POSTGRES_PASSWORD\n      hostname:\n        env: DAGSTER_POSTGRES_HOST\n      db_name:\n        env: DAGSTER_POSTGRES_DB\n      port: 5432" \
    > $DAGSTER_HOME/dagster.yaml

WORKDIR /opt/dagster/app

COPY workspace.yaml .