FROM python:3.11-slim

RUN pip install --no-cache-dir --timeout=300 --retries=5 dagster==1.7.7
RUN pip install --no-cache-dir --timeout=300 --retries=5 dagster-postgres==0.23.7 dagster-pipes==1.7.7
RUN pip install --no-cache-dir --timeout=300 --retries=5 psycopg2-binary==2.9.9 redis==5.0.4
RUN pip install --no-cache-dir --timeout=300 --retries=5 boto3==1.34.69 pandas==2.2.2
RUN pip install --no-cache-dir --timeout=300 --retries=5 scikit-learn==1.4.2 joblib==1.4.2
RUN pip install --no-cache-dir --timeout=300 --retries=5 kafka-python==2.0.2

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

WORKDIR /opt/dagster/app

COPY pipelines/ .

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "pipeline.py"]